package com.lyihub.archiveassistant.domain

object SampleKnowledgeData {
  /** Default fallback ministry ID; corresponds to [SixMinistry.TREASURY]. */
  const val DefaultTopicId = "treasury"

  /** The six canonical ministry topics derived from [SixMinistry]. */
  val topics: List<Topic> = sixMinistryTopics

  val items: List<KnowledgeItem> =
    listOf(
      KnowledgeItem(
        id = "item-officials-blog-list",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "中文博客琅琊榜",
        summary = "qianguyihao 维护的中文独立博客索引，适合作为作者和信息源人脉库入口。",
        fullText = "中文博客琅琊榜收录持续更新、高质量、阅读体验良好的独立博客，可用于维护长期关注的作者和站点名单。",
        sourceUrl = "https://github.com/qianguyihao/blog-list",
        createdAtEpochMillis = 1_720_000_000_000,
      ),
      KnowledgeItem(
        id = "item-officials-martinliu",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Martin Liu 的 DevOps 博客",
        summary = "DevOps China 创始人的个人博客，适合存为工程作者档案和长期订阅来源。",
        fullText = "Martin Liu's Blog 包含 DevOps、云原生、Gateway API、Jenkins 替代方案等文章，可归档为特定博主来源。",
        sourceUrl = "https://martinliu.cn/",
        createdAtEpochMillis = 1_720_086_400_000,
      ),
      KnowledgeItem(
        id = "item-officials-heibaimeng",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "黑白梦技术博客",
        summary = "围绕 Agent、RAG、Transformers.js 和前端工程实践的技术博客作者源。",
        fullText = "黑白梦博客发布 Agent 会话与记忆管理、RAG 检索增强生成、Transformers.js 本地化模型等系列文章。",
        sourceUrl = "https://heibaimeng.com/",
        createdAtEpochMillis = 1_720_172_800_000,
      ),
      KnowledgeItem(
        id = "item-officials-lategege",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "lategege 的技术博客",
        summary = "AI、安卓、后端和开发效率方向的个人技术博客，可作为博主 WEB_ARTICLE 档案。",
        fullText = "lategege 的技术博客归档了 Docker 容器化、Linux 内核、WordPress 迁移 Hugo、私人音乐服务等实践文章。",
        sourceUrl = "https://lategege.com/",
        imageResName = "article_officials_004_lategege_kernel",
        createdAtEpochMillis = 1_720_259_200_000,
      ),
      KnowledgeItem(
        id = "item-treasury-sspai-alipay",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "自己分析支付宝账单",
        summary = "少数派文章介绍导出支付宝 CSV 并构建账单分析网页，包含账单截图和字段说明。",
        fullText = "文章从支付宝交易流水证明导出、CSV 字段结构、年度总览、分类分析、热力图和隐私缓存策略展开。",
        sourceUrl = "https://sspai.com/post/96151",
        imageResName = "article_treasury_001_sspai_alipay",
        createdAtEpochMillis = 1_720_345_600_000,
      ),
      KnowledgeItem(
        id = "item-treasury-python-bill-report",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "Python 合并微信与支付宝账单",
        summary = "何俊杰的教程用 pandas 合并账单 CSV，并生成 Markdown 财务报告。",
        fullText = "教程包含支付宝 skiprows、微信列名映射、金额清洗、收支分组统计和最终账单 Markdown 生成代码。",
        sourceUrl = null,
        fileName = "alipay-wechat-finance.md",
        createdAtEpochMillis = 1_720_432_000_000,
      ),
      KnowledgeItem(
        id = "item-treasury-personal-finance",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "我是如何统计个人财务状况的",
        summary = "Justin Yan 分享统一账户、交易类型、转账排除和自动分类的个人财务统计方法。",
        fullText = "文章把账户分为信用卡、活期、理财、股票等类别，并强调转账不能重复计入支出。",
        sourceUrl = "https://justinyan.me/post/4427",
        imageResName = "article_treasury_003_personal_finance",
        createdAtEpochMillis = 1_720_518_400_000,
      ),
      KnowledgeItem(
        id = "item-treasury-bill-books",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "Bill_books 自动账单统计",
        summary = "开源项目 README 记录微信、支付宝账单下载、过滤规则和自动分类配置。",
        fullText = "Do-er/Bill_books 支持批量微信与支付宝账单统计、重复订单去除、退款过滤、工资卡设置和 HTML 图形化视图。",
        sourceUrl = null,
        fileName = "Bill_books_README.md",
        createdAtEpochMillis = 1_720_604_800_000,
      ),
      KnowledgeItem(
        id = "item-rites-d2l",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.PDF,
        title = "动手学深度学习",
        summary = "面向中文读者的深度学习教材，在线文档提供 PDF、Jupyter 和代码资源。",
        fullText = "《动手学深度学习》包含线性网络、CNN、RNN、Transformer、优化算法和 NLP 等章节，适合作为长文档学习输入。",
        sourceUrl = null,
        fileName = "d2l-zh-pytorch.pdf",
        imageResName = "article_rites_001_d2l_front",
        createdAtEpochMillis = 1_720_691_200_000,
      ),
      KnowledgeItem(
        id = "item-rites-pumpkin-book",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.PDF,
        title = "南瓜书：机器学习公式详解",
        summary = "Datawhale 开源的西瓜书公式推导补充材料，适合作为 PDF 学习档案。",
        fullText = "南瓜书围绕周志华《机器学习》的公式推导进行补充，提供 GitHub、PDF release、勘误和学习资源。",
        sourceUrl = null,
        fileName = "pumpkin-book.pdf",
        imageResName = "article_rites_002_pumpkin_book",
        createdAtEpochMillis = 1_720_777_600_000,
      ),
      KnowledgeItem(
        id = "item-rites-ruanyifeng-weekly",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "科技爱好者周刊",
        summary = "阮一峰长期维护的技术与信息输入周刊，适合归档为高质量网页文章源。",
        fullText = "科技爱好者周刊收集科技新闻、工具、文章和观点，可作为持续学习输入和信息筛选样本。",
        sourceUrl = "https://github.com/ruanyf/weekly",
        imageResName = "article_rites_003_ruanyifeng_weekly",
        createdAtEpochMillis = 1_720_864_000_000,
      ),
      KnowledgeItem(
        id = "item-rites-countries-note",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "《国家的常识》读书笔记",
        summary = "思涯谷读书笔记，围绕比较政治、地理、文化和制度进行结构化整理。",
        fullText = "笔记总结英国、法国、德国、日本、俄罗斯、印度等国家的历史、制度、政治文化和现实争论。",
        sourceUrl =
          "https://baohuiming.net/post/countries-and-concepts-politics-geography-culture-notes",
        createdAtEpochMillis = 1_720_950_400_000,
      ),
      KnowledgeItem(
        id = "item-military-open-health-agent",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Open Health Agent",
        summary = "开源 AI 健康顾问 Agent，统一收集、保存并分析个人健康数据。",
        fullText =
          "Open Health Agent 使用 Bun、TypeScript、SQLite、Drizzle、Hono 和 Vue，支持微信、QQ Bot 与 WebSocket 通道。",
        sourceUrl = "https://github.com/yaotutu/open-health-agent",
        imageResName = "article_military_001_open_health_agent",
        createdAtEpochMillis = 1_721_036_800_000,
      ),
      KnowledgeItem(
        id = "item-military-health-coach",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "health-coach 开源健康教练",
        summary = "开源 AI 健康教练技能，覆盖饮食照片分析、体检指标、训练和补剂建议。",
        fullText =
          "H1an1/health-coach 提供 nutrition、medical-markers、exercise、supplements、medications 等 Markdown 知识库。",
        sourceUrl = null,
        fileName = "health-coach_README.md",
        createdAtEpochMillis = 1_721_123_200_000,
      ),
      KnowledgeItem(
        id = "item-military-ai-health-vault",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "AI + Obsidian 健康管理系统",
        summary = "用模板、Prompt 和搭建指南为自己和家人建立私有化健康档案。",
        fullText = "ai-health-vault 的 prompts 包含体检报告提取、药盒识别、趋势分析、就医准备、Apple Watch 数据分析等工作流。",
        sourceUrl = null,
        fileName = "ai-health-vault_README_CN.md",
        createdAtEpochMillis = 1_721_209_600_000,
      ),
      KnowledgeItem(
        id = "item-military-personal-health-ai",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "个人健康资料 AI 分析流程",
        summary = "Wisely Chen 介绍用 AI、Apple 健康导出和图片资料整理健康数据的实际流程。",
        fullText = "文章覆盖 Apple 健康 ZIP/XML 导出、健检报告图片抽取、Markdown 输出和本地运行隐私注意事项。",
        sourceUrl = "https://ai-coding.wiselychen.com/personal-health-data-ai-analysis-system/",
        imageResName = "article_military_004_personal_health_ai",
        createdAtEpochMillis = 1_721_296_000_000,
      ),
      KnowledgeItem(
        id = "item-justice-anti-fraud-guide",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "国家反诈中心防骗指南",
        summary = "公安部刑侦局反诈宣传入口，适合作为高权重规则和防坑指南样本。",
        fullText = "国家反诈中心发布刷单返利、虚假投资理财、冒充客服、冒充公检法等诈骗类型的识别和防范提示。",
        sourceUrl = "https://www.mps.gov.cn/n2254098/n4904352/index.html",
        createdAtEpochMillis = 1_721_382_400_000,
      ),
      KnowledgeItem(
        id = "item-justice-consumer-warning",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "中国消费者协会消费警示",
        summary = "中消协消费提示和警示栏目，可归档为购物防坑和维权规则来源。",
        fullText = "中国消费者协会发布商品服务消费提示、维权案例和风险警示，适合构建防坑指南主题。",
        sourceUrl = "https://www.cca.org.cn/xxgz/detail/30450.html",
        createdAtEpochMillis = 1_721_468_800_000,
      ),
      KnowledgeItem(
        id = "item-justice-bill-filter-rules",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "账单过滤与无效数据规则",
        summary = "Bill_books README 中的退款、交易关闭、0 元订单等过滤规则，适合作为稽核样本。",
        fullText = "规则列出退款成功、交易关闭、还款成功、金额为 0 或 0.1、不记收支等低权重或应排除记录。",
        sourceUrl = null,
        fileName = "bill-filter-rules.md",
        createdAtEpochMillis = 1_721_555_200_000,
      ),
      KnowledgeItem(
        id = "item-justice-sspai-bill-screenshots",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.IMAGE_SCREENSHOT,
        title = "支付宝账单贴纸干扰截图",
        summary = "少数派文章中的支付宝账单界面截图，用于标记低价值贴纸和界面噪声。",
        fullText = "作者指出账单页面的日常贴纸待领取干扰了账单分析入口，可作为低质量但不删除内容的稽核样本。",
        sourceUrl = null,
        fileName = "alipay-sticker-noise.png",
        createdAtEpochMillis = 1_721_641_600_000,
      ),
      KnowledgeItem(
        id = "item-works-raspberry-pi",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "树莓派玩法总结",
        summary = "思涯谷的树莓派系统优化和功能配置教程，适合工程实操归档。",
        fullText = "文章汇总安装系统、SSH、屏幕旋转、网络配置、软件安装和硬件控制等树莓派使用方法。",
        sourceUrl = "https://baohuiming.net/post/raspberry-pi",
        imageResName = "article_works_001_raspberry_pi",
        createdAtEpochMillis = 1_721_728_000_000,
      ),
      KnowledgeItem(
        id = "item-works-openclaw-feishu",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "树莓派部署 OpenClaw + 飞书机器人",
        summary = "在树莓派 5 上部署 OpenClaw 汉化版并集成飞书机器人的实操教程。",
        fullText = "教程覆盖 Arch Linux、OpenClaw 网关、飞书机器人集成和本地 AI 助手运行，适合项目实操主题。",
        sourceUrl = "https://baohuiming.net/post/arch-linux-openclaw-feishu-tutorial",
        createdAtEpochMillis = 1_721_814_400_000,
      ),
      KnowledgeItem(
        id = "item-works-maomi-framework",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Maomi 框架事件总线教程",
        summary = "痴者工良的 .NET 高级开发系列，讲解事件总线框架和源码实践。",
        fullText = "文章结合作者博客、教程文档和 GitHub 源码，讨论事件总线在 DDD 模块解耦中的实现。",
        sourceUrl = "https://www.whuanle.cn/",
        createdAtEpochMillis = 1_721_900_800_000,
      ),
      KnowledgeItem(
        id = "item-works-health-agent-repo",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "小卡健康 Agent 仓库",
        summary = "本地文件驱动的 AI 健康助手项目，包含规则、模板、知识库和脚本。",
        fullText =
          "xiaoka-health-agent 的仓库结构包括 agent.md、SOUL.md、SKILL.md、config、templates、references、docs、fixtures 和 scripts。",
        sourceUrl = null,
        fileName = "xiaoka-health-agent_README.md",
        createdAtEpochMillis = 1_721_987_200_000,
      ),
      KnowledgeItem(
        id = "item-officials-zellij-plugins",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Zellij 插件作者生态",
        summary = "Zellij 官方插件文档和社区插件入口，适合沉淀终端工具作者与维护者名录。",
        fullText = "Zellij plugins 文档展示 Rust/WASM 插件接口、官方示例和社区扩展，可作为寻找独立开发者与终端工作流作者的入口。",
        sourceUrl = "https://zellij.dev/documentation/plugins",
        createdAtEpochMillis = 1_722_073_600_000,
      ),
      KnowledgeItem(
        id = "item-officials-ghostty-config",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Ghostty 配置参考",
        summary = "Ghostty 官方配置参考可用于归档终端玩家、配置作者和高质量 dotfiles 来源。",
        fullText = "Ghostty configuration reference 覆盖字体、主题、键位、窗口和平台差异，是收集终端配置作者与插件生态资料的基础链接。",
        sourceUrl = "https://ghostty.org/docs/config/reference",
        imageResName = "article_officials_006_ghostty_config",
        createdAtEpochMillis = 1_722_160_000_000,
      ),
      KnowledgeItem(
        id = "item-officials-contact-card-screenshot",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.IMAGE_SCREENSHOT,
        title = "展会供应商名片截图",
        summary = "显示面板供应商联系人名片的本地 mock 截图，用于测试从商务名片提取姓名、职位、电话和微信。",
        fullText = "截图模拟展会上互加微信后保存的供应商名片，包含公司、联系人、职位、手机号、微信和产品方向字段。",
        sourceUrl = null,
        fileName = "supplier-contact-card.png",
        createdAtEpochMillis = 1_722_246_400_000,
      ),
      KnowledgeItem(
        id = "item-officials-team-roster",
        topicId = SixMinistry.OFFICIALS.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "工作室成员分工备忘",
        summary = "内部协作名录样例，记录成员职责、技能、排期偏好和对接边界。",
        fullText = "本地 Markdown 夹具模拟工作室成员分工和兼职协作者技能档案，便于验证人脉/组织类文档归档。",
        sourceUrl = null,
        fileName = "studio-team-roster.md",
        createdAtEpochMillis = 1_722_332_800_000,
      ),
      KnowledgeItem(
        id = "item-treasury-amd-board-guide",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "AMD Ryzen 主板选购指南",
        summary = "GamersNexus 的主板评测和选购内容，可作为高性能测试平台采买参考。",
        fullText = "GamersNexus motherboard reviews 覆盖供电、BIOS、散热和平台兼容性，适合归档为硬核装备采买清单来源。",
        sourceUrl = "https://gamersnexus.net/cat/motherboards",
        createdAtEpochMillis = 1_722_419_200_000,
      ),
      KnowledgeItem(
        id = "item-treasury-cloud-api-bill",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.IMAGE_SCREENSHOT,
        title = "云端大模型 API 月账单截图",
        summary = "OpenAI、Gemini、Anthropic 多模型调用成本的本地 mock 截图。",
        fullText = "截图模拟独立工作室月度模型 API 成本面板，包含 token、推理请求、缓存命中和供应商分摊字段。",
        sourceUrl = null,
        fileName = "cloud-api-bill.png",
        createdAtEpochMillis = 1_722_505_600_000,
      ),
      KnowledgeItem(
        id = "item-treasury-quarterly-budget",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "独立工作室季度预算",
        summary = "本地 Markdown 预算表，覆盖云服务、设备租赁、内容制作和差旅支出。",
        fullText = "预算夹具包含 CAPEX、OPEX、订阅续费、设备租赁合同摘要和风险预留，便于测试财务文档归档。",
        sourceUrl = null,
        fileName = "studio-quarterly-budget.md",
        createdAtEpochMillis = 1_722_592_000_000,
      ),
      KnowledgeItem(
        id = "item-treasury-saas-renewal-register",
        topicId = SixMinistry.TREASURY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "SaaS 续费管理清单方法",
        summary = "Vendr 的 SaaS renewal checklist，适合记录订阅周期、负责人和续费窗口。",
        fullText = "文章解释续费前的用量审计、合同条款、价格涨幅、谈判窗口和负责人协作，可作为资产维护样本。",
        sourceUrl = "https://www.vendr.com/blog/saas-renewal-checklist",
        createdAtEpochMillis = 1_722_678_400_000,
      ),
      KnowledgeItem(
        id = "item-rites-nvidia-blackwell",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.PDF,
        title = "NVIDIA Blackwell 架构白皮书",
        summary = "Blackwell GPU 架构、第二代 Transformer Engine 和 NVLink 的技术白皮书摘要夹具。",
        fullText = "本地 PDF 夹具记录 Blackwell 架构要点、FP4 推理、RAS、Confidential Computing 和多 GPU 互连信息。",
        sourceUrl = null,
        fileName = "nvidia-blackwell-architecture.pdf",
        imageResName = "article_rites_005_nvidia_blackwell",
        createdAtEpochMillis = 1_722_764_800_000,
      ),
      KnowledgeItem(
        id = "item-rites-apple-m-memory-bandwidth",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Apple M 系列统一内存带宽解释",
        summary = "AnandTech 对 Apple Silicon 内存带宽和 SoC 架构的技术分析。",
        fullText = "文章分析 M 系列 SoC 的统一内存、带宽标称、缓存层级和图形/神经引擎共享资源，适合做硬件深读资料。",
        sourceUrl = "https://www.anandtech.com/show/16226/apple-silicon-m1-a14-deep-dive",
        createdAtEpochMillis = 1_722_851_200_000,
      ),
      KnowledgeItem(
        id = "item-rites-moe-paper",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.PDF,
        title = "Switch Transformer MoE 论文",
        summary = "稀疏激活专家模型的经典论文摘要夹具，用于 MoE 深度研读归档。",
        fullText =
          "本地 PDF 夹具总结 Switch Transformer 的 sparse expert routing、capacity factor、训练稳定性和参数规模扩展。",
        sourceUrl = null,
        fileName = "switch-transformer-moe.pdf",
        createdAtEpochMillis = 1_722_937_600_000,
      ),
      KnowledgeItem(
        id = "item-rites-hdr-color-standard",
        topicId = SixMinistry.RITES.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "10-bit HDR 与 5K120 色彩管理笔记",
        summary = "高级色彩管理学习笔记，覆盖 10-bit、HDR、P3、BT.2020 和高刷新显示链路。",
        fullText = "本地 Markdown 夹具用于归档显示标准、校色流程、光谱亮度计读数和内容制作交付规范。",
        sourceUrl = null,
        fileName = "hdr-color-management-notes.md",
        createdAtEpochMillis = 1_723_024_000_000,
      ),
      KnowledgeItem(
        id = "item-military-dify-docs",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Dify 应用编排指南",
        summary = "Dify 官方文档中的工作流与 Agent 编排入口，适合效率工具库归档。",
        fullText = "Dify docs 覆盖聊天助手、Agent、工作流、知识库、工具调用和部署配置，可作为生产力兵器库入口。",
        sourceUrl = "https://docs.dify.ai/",
        imageResName = "article_military_005_dify_docs",
        createdAtEpochMillis = 1_723_110_400_000,
      ),
      KnowledgeItem(
        id = "item-military-ohmyopenagent",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "OpenAgent 工具链集合",
        summary = "OpenAgent 相关工具和模板入口，适合沉淀 CLI 与自动化工具链。",
        fullText = "OpenAgent 工具链资料可用于整理提示词、命令行工具和多 Agent 协作配置，归档为效率工具库来源。",
        sourceUrl = "https://github.com/langchain-ai/open-agent-platform",
        createdAtEpochMillis = 1_723_196_800_000,
      ),
      KnowledgeItem(
        id = "item-military-smartwatch-weekly",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.IMAGE_SCREENSHOT,
        title = "智能手表周度运动睡眠截图",
        summary = "本地健康面板截图，展示睡眠、HRV、训练负荷和恢复状态。",
        fullText = "截图模拟智能手表周报，用于测试个人健康和体能指标图片归档与摘要。",
        sourceUrl = null,
        fileName = "smartwatch-weekly-health.png",
        createdAtEpochMillis = 1_723_283_200_000,
      ),
      KnowledgeItem(
        id = "item-military-zep-memory-notes",
        topicId = SixMinistry.MILITARY.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "Zep Cloud 长记忆 Prompt 调优",
        summary = "战术自动化编排笔记，记录大模型长记忆图谱、检索窗口和提示词约束。",
        fullText = "本地 Markdown 夹具整理 Zep Cloud memory、session、事实抽取、长期偏好和自动化工作流编排草图。",
        sourceUrl = null,
        fileName = "zep-memory-prompt-notes.md",
        createdAtEpochMillis = 1_723_369_600_000,
      ),
      KnowledgeItem(
        id = "item-justice-gb-headlamp-standard",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.PDF,
        title = "GB 19152-2025 摩托车前照灯标准",
        summary = "摩托车及轻便摩托车前照灯强制性标准摘要夹具，适合作为不可逾越法规样本。",
        fullText = "本地 PDF 夹具记录 GB 19152-2025 的适用范围、光色、配光性能、试验方法和合规检查要点。",
        sourceUrl = null,
        fileName = "gb-19152-2025-headlamp.pdf",
        createdAtEpochMillis = 1_723_456_000_000,
      ),
      KnowledgeItem(
        id = "item-justice-apache-license",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Apache License 2.0 官方文本",
        summary = "开源协议官方说明，用于归档授权、专利条款和 NOTICE 要求。",
        fullText = "Apache License 2.0 包含版权授予、专利授权、再分发条件、商标限制和责任免责声明，是法律规则样本。",
        sourceUrl = "https://www.apache.org/licenses/LICENSE-2.0",
        createdAtEpochMillis = 1_723_542_400_000,
      ),
      KnowledgeItem(
        id = "item-justice-ai-hackathon-rules",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "AI 黑客大乱斗赛制与裁判规则",
        summary = "AWD 模式比赛规则夹具，包含违规判定、计分、封禁和 AI 裁判提示词约束。",
        fullText = "本地 Markdown 夹具模拟 AI 安全竞赛规则、LLM Caster 裁判边界和申诉流程，用于刑部规则归档。",
        sourceUrl = null,
        fileName = "ai-hackathon-rules.md",
        createdAtEpochMillis = 1_723_628_800_000,
      ),
      KnowledgeItem(
        id = "item-justice-low-confidence-quarantine",
        topicId = SixMinistry.JUSTICE.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "低置信碎片留校察看清单",
        summary = "LocalLlmClassifier 低置信样本的隔离清单，定期复核或批量清空。",
        fullText = "本地 Markdown 夹具记录标题党、重复链接、无上下文截图和分类置信度过低的碎片处理规则。",
        sourceUrl = null,
        fileName = "low-confidence-quarantine.md",
        createdAtEpochMillis = 1_723_715_200_000,
      ),
      KnowledgeItem(
        id = "item-works-vivo-fold-script",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.DOCUMENT,
        documentFormat = DocumentFormat.MARKDOWN,
        title = "Vivo X Fold 6 体验视频脚本",
        summary = "内容创作工程夹具，包含折叠屏系统软实力体验、分镜和 B-roll 清单。",
        fullText = "本地 Markdown 夹具模拟 OriginOS Fold 体验视频脚本，覆盖开场、系统动效、多任务、外屏内屏切换和素材需求。",
        sourceUrl = null,
        fileName = "vivo-x-fold-video-script.md",
        imageResName = "article_works_005_vivo_fold_script",
        createdAtEpochMillis = 1_723_801_600_000,
      ),
      KnowledgeItem(
        id = "item-works-docker-controlled-env",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "Docker Compose 官方教程",
        summary = "Docker 官方 Compose 文档，适合归档本地受控环境搭建步骤。",
        fullText =
          "Docker Compose docs 覆盖 compose.yaml、services、volumes、networks、profiles 和多容器环境复现，是工程搭建样本。",
        sourceUrl = "https://docs.docker.com/compose/",
        imageResName = "article_works_006_docker_compose",
        createdAtEpochMillis = 1_723_888_000_000,
      ),
      KnowledgeItem(
        id = "item-works-opencode-github",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "OpenCode 本地运行仓库",
        summary = "OpenCode GitHub 仓库，适合作为本地编码 Agent 环境搭建资料。",
        fullText = "OpenCode 仓库记录安装、运行、配置和开发 Agent 的入口，可归档为本地部署与环境搭建样本。",
        sourceUrl = "https://github.com/sst/opencode",
        imageResName = "article_works_007_opencode",
        createdAtEpochMillis = 1_723_974_400_000,
      ),
      KnowledgeItem(
        id = "item-works-yolo-mahjong",
        topicId = SixMinistry.WORKS.id,
        contentType = ContentType.WEB_ARTICLE,
        title = "YOLOv8 自定义数据集训练文档",
        summary = "Ultralytics 官方训练文档，可用于麻将牌识别、标注和推理流程归档。",
        fullText = "Ultralytics train mode 文档说明数据集 YAML、模型选择、训练参数、验证和导出，适合 DIY 视觉项目。",
        sourceUrl = "https://docs.ultralytics.com/modes/train/",
        imageResName = "article_works_008_ultralytics_train",
        createdAtEpochMillis = 1_724_060_800_000,
      ),
    )

  val defaultAiEngineSettings = AiEngineSettings(localModelId = GEMMA_4_E4B_IT.id)
}
